# Generated by Django 2.2.24 on 2022-05-28 13:19

from django.db import migrations

from property.models import Owner


def add_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            owners_phonenumber=flat.owners_phonenumber,
            defaults={
                'owner': flat.owner,
                'pure_phone': flat.owner_pure_phone
            }
        )
        owner.flats_own.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(add_owner)
    ]
